import type { Config } from "tailwindcss";

// Paleta e tokens extraídos do mockup original (index.html) do ETEC Quest,
// para que o app gerado tenha exatamente a mesma identidade visual.
const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#005ac2",
        outline: "#8c909f",
        "surface-container-low": "#131b2e",
        "tertiary-fixed": "#d8e3fb",
        "primary-fixed-dim": "#adc6ff",
        "secondary-fixed": "#ffddb8",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#3c475a",
        "surface-bright": "#31394e",
        "surface-variant": "#2d3449",
        "primary-fixed": "#d8e2ff",
        "on-secondary-fixed": "#2a1700",
        "on-primary-container": "#00285d",
        "on-surface-variant": "#c2c6d6",
        "surface-container-high": "#222a3e",
        "on-primary-fixed": "#001a42",
        error: "#ffb4ab",
        "tertiary-container": "#8691a7",
        "on-secondary": "#472a00",
        "on-error": "#690005",
        "on-surface": "#dbe2fd",
        secondary: "#ffb95f",
        surface: "#0b1326",
        "on-primary": "#002e6a",
        "secondary-fixed-dim": "#ffb95f",
        "surface-container-lowest": "#060d20",
        "on-primary-fixed-variant": "#004395",
        "on-background": "#dbe2fd",
        background: "#0b1326",
        "on-secondary-fixed-variant": "#653e00",
        "on-tertiary-container": "#1f2a3c",
        "surface-container": "#171f33",
        "on-error-container": "#ffdad6",
        "secondary-container": "#8f5a00",
        "surface-tint": "#adc6ff",
        "inverse-on-surface": "#283044",
        "tertiary-fixed-dim": "#bcc7de",
        "on-tertiary": "#263143",
        "outline-variant": "#424754",
        "primary-container": "#4d8eff",
        "inverse-surface": "#dbe2fd",
        "on-tertiary-fixed": "#111c2d",
        tertiary: "#bcc7de",
        "surface-dim": "#0b1326",
        "on-secondary-container": "#ffdfbc",
        primary: "#adc6ff",
        "surface-container-highest": "#2d3449",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        sm: "8px",
        "margin-mobile": "16px",
        xs: "4px",
        unit: "4px",
        gutter: "24px",
        lg: "24px",
        "margin-desktop": "64px",
        xl: "48px",
        md: "16px",
      },
      fontFamily: {
        "body-lg": ["Sora", "sans-serif"],
        "label-sm": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        display: ["Sora", "sans-serif"],
        "body-md": ["Sora", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
